{
 "title": "SRE Service Observability Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (http_target) (\n  rate(\n    http_server_duration_milliseconds_count{\n      exported_job=\"sre-demo-service\"\n    }[5m]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  http_server_active_requests{\n    exported_job=\"sre-demo-service\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 5xx Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(\n  rate(\n    http_server_duration_milliseconds_count{\n      exported_job=\"sre-demo-service\",\n      http_status_code=~\"5..\"\n    }[5m]\n  )\n)\n/\nsum(\n  rate(\n    http_server_duration_milliseconds_count{\n      exported_job=\"sre-demo-service\"\n    }[5m]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(\n      http_server_duration_milliseconds_bucket{\n        exported_job=\"sre-demo-service\"\n      }[5m]\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    http_server_duration_milliseconds_count{\n      exported_job=\"sre-demo-service\"\n    }[1m]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}